=== jimregan/apertium-svn-2008/trunk/apertium-lexical-webform/private/paradigmas.fr-es/form.dtd
<!--
      DTD for the format of form entries
-->
<!ELEMENT form (entry)+>
	<!-- root element-->
<!ATTLIST form
	lang CDATA #REQUIRED
	langpair CDATA #REQUIRED
>
<!ELEMENT entry (endings, paradigms)+>
	<!-- entry -->
<!ATTLIST entry
	PoS CDATA #REQUIRED
	nbr CDATA #IMPLIED
	gen CDATA #IMPLIED
>	
<!ELEMENT endings (stem, ending+)>
	<!-- examples (stem and endings) for paradigms -->


<!ELEMENT stem (#PCDATA)>

<!ELEMENT ending (#PCDATA)>


<!ELEMENT paradigms (par+)>
	<!--paradigms used to build new entries-->

<!ATTLIST paradigms
	howmany CDATA #REQUIRED
>
<!--number of paradigms used to build new entries-->

<!ELEMENT par EMPTY>
         <!-- reference to paradigm -->
<!ATTLIST par
	n CDATA #REQUIRED
>
   <!-- n: paradigm name -->

=== jimregan/apertium-svn-2008/local/apertium-lexical-webform/private/paradigmas.es-pt/paradig.es-pt.es.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE form SYSTEM "form.dtd">
<form lang="es" langpair="es-pt">

    <entry PoS="adj" nbr="sg_pl" gen="m f">
	<endings>
		<stem>abrumador</stem>
		<ending></ending>
		<ending>a</ending>
		<ending>s</ending>
		<ending>as</ending>
	</endings>
	<paradigms howmany="1">
		<par n="abrumador__adj"/>
	</paradigms>
</entry>


    <entry PoS="adj" nbr="sg_pl" gen="mf">
	<endings>
		<stem>abdominal</stem>
		<ending></ending>
		<ending>es</ending>
	</endings>
	<paradigms howmany="1">
		<par n="accidental__adj"/>
	</paradigms>
</entry>


    <entry PoS="adj" nbr="sg_pl" gen="mf">
	<endings>
		<stem>abundante</stem>
		<ending></ending>
		<ending>s</ending>
	</endings>
	<paradigms howmany="1">
		<par n="aceptable__adj"/>
	</paradigms>
</entry>


    <entry PoS="adj" nbr="sp" gen="mf">
	<endings>
		<stem>multimedia</stem>
		<ending/>
	</endings>
	<paradigms howmany="1">
		<par n="anti__adj"/>
	</paradigms>
</entry>



    <entry PoS="adj" nbr="sg_pl" gen="m f">
	<endings>
		<stem>absolut</stem>
		<ending>o</ending>
		<ending>a</ending>
		<ending>os</ending>
		<ending>as</ending>
	</endings>
	<paradigms howmany="1">
		<par n="abiert/o__adj"/>
	</paradigms>
</entry>



    <entry PoS="adj" nbr="sg_pl" gen="m f">
	<endings>
		<stem>andalu</stem>
		<ending>z</ending>
		<ending>za</ending>
		<ending>ces</ending>
		<ending>zas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="jue/z__adj"/>
	</paradigms>
</entry>


    <entry PoS="adj" nbr="sg_pl" gen="mf">
	<endings>
		<stem>atro</stem>
		<ending>z</ending>
		<ending>ces</ending>
	</endings>
	<paradigms howmany="1">
		<par n="capa/z__adj"/>
	</paradigms>
</entry>


    <entry PoS="adj" nbr="sg_pl" gen="m f">
	<endings>
		<stem>alem</stem>
		<ending>án</ending>
		<ending>ana</ending>
		<ending>anes</ending>
		<ending>anas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="alem/án__adj"/>
	</paradigms>
</entry>

    <entry PoS="adj" nbr="sg_pl" gen="m f">
	<endings>
		<stem>aragon</stem>
		<ending>és</ending>
		<ending>esa</ending>
		<ending>eses</ending>
		<ending>esas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="alban/és__adj"/>
	</paradigms>
</entry>



    <entry PoS="adj" nbr="sg_pl" gen="m f">
	<endings>
		<stem>anfitri</stem>
		<ending>ón</ending>
		<ending>ona</ending>
		<ending>ones</ending>
		<ending>onas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="besuc/ón__adj"/>
	</paradigms>
</entry>


    <entry PoS="adj" nbr="sg_pl" gen="mf">
	<endings>
		<stem>com</stem>
		<ending>ún</ending>
		<ending>unes</ending>
	</endings>
	<paradigms howmany="1">
		<par n="com/ún__adj"/>
	</paradigms>
</entry>


    <entry PoS="adv">
	<endings>
		<stem>ahora</stem>
		<ending/>
	</endings>
	<paradigms howmany="1">
		<par n="Op.Cit.__adv"/>
	</paradigms>
</entry>


    <entry PoS="cnjadv">
	<endings>
		<stem>porque</stem>
		<ending/>
	</endings>
	<paradigms howmany="1">
		<par n="a_buen_seguro__cnjadv"/>
	</paradigms>
</entry>
		
    <entry PoS="cnjsub">
	<endings>
		<stem>que</stem>
		<ending/>
	</endings>
	<paradigms howmany="1">
		<par n="que__cnjsub"/>
	</paradigms>
</entry>
		
		

    <entry PoS="acr" nbr="sg" gen="f">
	<endings>
		<stem>BBC</stem>
		<ending/>
	</endings>
	<paradigms howmany="1">
		<par n="AFP__n"/>
	</paradigms>
</entry>


    <entry PoS="acr" nbr="sg" gen="m">
	<endings>
		<stem>FBI</stem>
		<ending/>
	</endings>
	<paradigms howmany="1">
		<par n="FBI__n"/>
	</paradigms>
</entry>


    <entry PoS="acr" nbr="sp" gen="m">
	<endings>
		<stem>ADN</stem>
		<ending/>
	</endings>
	<paradigms howmany="1">
		<par n="ADN__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sp" gen="mf">
	<endings>
		<stem>ATS</stem>
		<ending/>
	</endings>
	<paradigms howmany="1">
		<par n="ATS__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="pl" gen="f">
	<endings>
		<stem>vacaciones</stem>
		<ending></ending>
	</endings>
	<paradigms howmany="1">
		<par n="vacaciones__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="m f">
	<endings>
		<stem>autor</stem>
		<ending></ending>
		<ending>a</ending>
		<ending>es</ending>
		<ending>as</ending>
	</endings>
	<paradigms howmany="1">
		<par n="acreedor__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="f">
	<endings>
		<stem>actitud</stem>
		<ending></ending>
		<ending>es</ending>
	</endings>
	<paradigms howmany="1">
		<par n="actitud__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="f">
	<endings>
		<stem>abeja</stem>
		<ending></ending>
		<ending>s</ending>
	</endings>
	<paradigms howmany="1">
		<par n="abadia__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="m f">
	<endings>
		<stem>alcalde</stem>
		<ending></ending>
		<ending>esa</ending>
		<ending>s</ending>
		<ending>esas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="alcalde__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg" gen="f">
	<endings>
		<stem>cuaresma</stem>
		<ending></ending>
	</endings>
	<paradigms howmany="1">
		<par n="d__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sp" gen="f">
	<endings>
		<stem>tesis</stem>
		<ending></ending>
	</endings>
	<paradigms howmany="1">
		<par n="crisis__n"/>
	</paradigms>
</entry>




    <entry PoS="noun" nbr="sg_pl" gen="m">
	<endings>
		<stem>abril</stem>
		<ending></ending>
		<ending>es</ending>
	</endings>
	<paradigms howmany="1">
		<par n="abril__n"/>
	</paradigms>
</entry>

    <entry PoS="noun" nbr="sg_pl" gen="m">
	<endings>
		<stem>abrigo</stem>
		<ending></ending>
		<ending>s</ending>
	</endings>
	<paradigms howmany="1">
		<par n="Este__n"/>
	</paradigms>
</entry>



    <entry PoS="noun" nbr="sp" gen="m">
	<endings>
		<stem>análisis</stem>
		<ending></ending>
	</endings>
	<paradigms howmany="1">
		<par n="analisis__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="mf">
	<endings>
		<stem>auxiliar</stem>
		<ending></ending>
		<ending>es</ending>
	</endings>
	<paradigms howmany="1">
		<par n="chofer__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="mf">
	<endings>
		<stem>accionista</stem>
		<ending></ending>
		<ending>s</ending>
	</endings>
	<paradigms howmany="1">
		<par n="accionista__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sp" gen="mf">
	<endings>
		<stem>guardaespaldas</stem>
		<ending></ending>
	</endings>
	<paradigms howmany="1">
		<par n="ex__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="f">
	<endings>
		<stem>im</stem>
		<ending>agen</ending>
		<ending>ágenes</ending>
	</endings>
	<paradigms howmany="1">
		<par n="im/agen__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="m">
	<endings>
		<stem>ex</stem>
		<ending>amen</ending>
		<ending>ámenes</ending>
	</endings>
	<paradigms howmany="1">
		<par n="ex/amen__n"/>
	</paradigms>
</entry>



    <entry PoS="noun" nbr="sg_pl" gen="m f">
	<endings>
		<stem>gobernant</stem>
		<ending>e</ending>
		<ending>a</ending>
		<ending>es</ending>
		<ending>as</ending>
	</endings>
	<paradigms howmany="1">
		<par n="gobernant/e__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="m">
	<endings>
		<stem>or</stem>
		<ending>igen</ending>
		<ending>ígenes</ending>
	</endings>
	<paradigms howmany="1">
		<par n="or/igen__n"/>
	</paradigms>
</entry>

    


    <entry PoS="noun" nbr="sg_pl" gen="m f">
	<endings>
		<stem>abogad</stem>
		<ending>o</ending>
		<ending>a</ending>
		<ending>os</ending>
		<ending>as</ending>
	</endings>
	<paradigms howmany="1">
		<par n="abogad/o__n"/>
	</paradigms>
</entry>



    <entry PoS="noun" nbr="sg_pl" gen="m">
	<endings>
		<stem>ajedre</stem>
		<ending>z</ending>
		<ending>ces</ending>
	</endings>
	<paradigms howmany="1">
		<par n="ajedre/z__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="f">
	<endings>
		<stem>actri</stem>
		<ending>z</ending>
		<ending>ces</ending>
	</endings>
	<paradigms howmany="1">
		<par n="actri/z__n"/>
	</paradigms>
</entry>

    <entry PoS="noun" nbr="sg_pl" gen="mf">
	<endings>
		<stem>portavo</stem>
		<ending>z</ending>
		<ending>ces</ending>
	</endings>
	<paradigms howmany="1">
		<par n="portavo/z__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="mf">
	<endings>
		<stem>jue</stem>
		<ending>z</ending>
		<ending>za</ending>
		<ending>ces</ending>
		<ending>zas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="jue/z__n"/>
	</paradigms>
</entry>

    <entry PoS="noun" nbr="sg_pl" gen="m f">
	<endings>
		<stem>alem</stem>
		<ending>án</ending>
		<ending>ana</ending>
		<ending>anes</ending>
		<ending>anas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="alem/án__n"/>
	</paradigms>
</entry>



    <entry PoS="noun" nbr="sg_pl" gen="m">
	<endings>
		<stem>and</stem>
		<ending>én</ending>
		<ending>enes</ending>
	</endings>
	<paradigms howmany="1">
		<par n="and/én__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="m f">
	<endings>
		<stem>alaban</stem>
		<ending>és</ending>
		<ending>esa</ending>
		<ending>eses</ending>
		<ending>esas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="alban/és__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="m">
	<endings>
		<stem>inter</stem>
		<ending>és</ending>
		<ending>eses</ending>
	</endings>
	<paradigms howmany="1">
		<par n="inter/és__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="m f">
	<endings>
		<stem>bailar</stem>
		<ending>ín</ending>
		<ending>ina</ending>
		<ending>ines</ending>
		<ending>inas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="bailar/ín__n"/>
	</paradigms>
</entry>


  
    <entry PoS="noun" nbr="sg_pl" gen="m f">
	<endings>
		<stem>anfitri</stem>
		<ending>ón</ending>
		<ending>ona</ending>
		<ending>ones</ending>
		<ending>onas</ending>
	</endings>
	<paradigms howmany="1">
		<par n="anfitri/ón__n"/>
	</paradigms>
</entry>


    <entry PoS="noun" nbr="sg_pl" gen="f">
	<endings>
		<stem>acci</stem>
		<ending>ón</ending>
		<ending>ones</ending>
